#!/bin/bash -e
# ==============================================================================
# Project Anvil - AMI Builder Layer
# scripts/install_app.sh
#
# This script is executed by Packer to build the Application Server Golden AMI.
# It installs PHP-FPM, the WordPress core files, a caching plugin, and the
# CloudWatch Agent, ensuring the base OS is ready for application deployment.
#
# Author: Carrick Bradley
# Last Updated: 2025-09-24
# ==============================================================================

# --- OS Package Installation ---
echo "--- [App AMI] Updating OS packages and installing PHP-FPM and extensions ---"
sudo apt-get update
sudo apt-get install -y unzip # Unzip for AWS CLI and W3TC plugin
# Install PHP-FPM and common extensions needed by WordPress, plus jq for scripts.
# The 'php-fpm' package will install the default PHP version for the OS.
sudo apt-get install -y php-fpm php-mysql php-curl php-gd php-mbstring php-xml php-xmlrpc php-soap php-intl php-zip jq

# --- AWS CLI Installation ---
echo "--- [App AMI] Installing AWS CLI v2 (official installer) ---"
curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "/tmp/awscliv2.zip"
unzip -q /tmp/awscliv2.zip -d /tmp
sudo /tmp/aws/install
aws --version

# --- Application Code Installation ---
echo "--- [App AMI] Unpacking core WordPress application files ---"
# The app_package.tar.gz artifact is uploaded to /tmp/ by Packer (from dist/ at workspace root).
sudo mkdir -p /var/www/wordpress
sudo tar -xzf /tmp/app_package.tar.gz -C /var/www/wordpress
sudo chown -R www-data:www-data /var/www/wordpress

# --- Caching Plugin Installation ---
echo "--- [App AMI] Installing W3 Total Cache plugin ---"
# Ensure the plugins directory exists before unzipping
sudo mkdir -p /var/www/wordpress/wp-content/plugins

# Dynamically get latest W3TC download link
W3TC_LATEST=$(curl -s "https://api.wordpress.org/plugins/info/1.2/?action=plugin_information&request[slug]=w3-total-cache" | jq -r .download_link)
if [[ -z "$W3TC_LATEST" || "$W3TC_LATEST" == "null" || "$W3TC_LATEST" == *"error"* ]]; then
  W3TC_LATEST="https://downloads.wordpress.org/plugin/w3-total-cache.latest-stable.zip" # Fallback
fi
wget "$W3TC_LATEST" -O /tmp/w3-total-cache.zip
sudo unzip /tmp/w3-total-cache.zip -d /var/www/wordpress/wp-content/plugins
rm /tmp/w3-total-cache.zip
echo "--- [App AMI] W3 Total Cache installed ---"

# CRITICAL: A wp-config.php file is NOT created in the AMI. It will be
# generated by a user_data script at instance launch to inject secrets.

# --- PHP-FPM Service Configuration ---
echo "--- [App AMI] Enabling PHP-FPM service to start on boot ---"
# Find the correct PHP-FPM service name (e.g., php8.1-fpm.service)
# This command lists all unit files and filters for patterns like 'phpX.Y-fpm.service'.
# 'head -n 1' takes the first match, assuming only one version of FPM is desired.
FPM_SERVICE=$(systemctl list-unit-files --type=service | grep -o 'php[0-9]\.[0-9]-fpm.service' | head -n 1)

if [ -n "$FPM_SERVICE" ]; then
  sudo systemctl enable "$FPM_SERVICE"
  # Also start the service immediately for the build (though it won't be serving traffic yet)
  sudo systemctl start "$FPM_SERVICE"
  echo "Enabled and started $FPM_SERVICE"
else
  echo "Error: Could not find an installed php-fpm service file (e.g., phpX.Y-fpm.service)." >&2
  # Exit with an error to ensure the Packer build fails if FPM service isn't found
  exit 1
fi

# --- CloudWatch Agent Installation ---
echo "--- [App AMI] Installing CloudWatch Agent ---"
wget https://s3.amazonaws.com/amazoncloudwatch-agent/ubuntu/amd64/latest/amazon-cloudwatch-agent.deb -O /tmp/amazon-cloudwatch-agent.deb
sudo dpkg -i -E /tmp/amazon-cloudwatch-agent.deb
rm /tmp/amazon-cloudwatch-agent.deb

# --- Debugging ---
# Show the instance profile info and AWS CLI identity.
echo "--- [Debug] EC2 Instance Profile Info (during AMI build) ---"
curl -s http://169.254.169.254/latest/meta-data/iam/info || echo "No IAM info available or instance not provisioned with IAM role"
aws sts get-caller-identity || echo "No AWS CLI identity or credentials available for current role"

echo "--- [App AMI] Golden AMI Build - App Server Complete ---"
