#!/bin/bash -e
# This script is run by Packer to build the Application Server Golden AMI.
# It installs PHP-FPM, the WordPress core files, a caching plugin, and the CloudWatch Agent.

echo "--- [App AMI] Updating OS packages ---"
sudo apt-get update
# Install PHP-FPM and common extensions needed by WordPress, plus unzip for plugins.
sudo apt-get install -y php-fpm php-mysql php-curl php-gd php-mbstring php-xml php-xmlrpc php-soap php-intl php-zip jq awscli unzip

# --- Application Code Installation ---
echo "--- [App AMI] Unpacking core WordPress application files ---"
# The app_package.tar.gz artifact is uploaded to /tmp/ by Packer.
sudo mkdir -p /var/www/wordpress
sudo tar -xzf /tmp/app_package.tar.gz -C /var/www/wordpress
sudo chown -R www-data:www-data /var/www/wordpress

# --- Caching Plugin Installation ---
echo "--- [App AMI] Installing W3 Total Cache plugin ---"
W3TC_LATEST=$(curl -s https://api.wordpress.org/plugins/info/1.2/?action=plugin_information&request[slug]=w3-total-cache | jq -r .download_link)
wget "$W3TC_LATEST" -O /tmp/w3-total-cache.zip
sudo unzip /tmp/w3-total-cache.zip -d /var/www/wordpress/wp-content/plugins
rm /tmp/w3-total-cache.zip
echo "--- [App AMI] W3 Total Cache installed ---"

# CRITICAL: A wp-config.php file is NOT created in the AMI. It will be
# generated by a user_data script at instance launch to inject secrets.

echo "--- [App AMI] Enabling PHP-FPM service to start on boot ---"
sudo systemctl enable php-fpm

# --- CloudWatch Agent Installation & Configuration ---
echo "--- [App AMI] Installing CloudWatch Agent ---"
wget https://s3.amazonaws.com/amazoncloudwatch-agent/ubuntu/amd64/latest/amazon-cloudwatch-agent.deb -O /tmp/amazon-cloudwatch-agent.deb
sudo dpkg -i -E /tmp/amazon-cloudwatch-agent.deb
rm /tmp/amazon-cloudwatch-agent.deb

echo "--- [App AMI] Configuring CloudWatch Agent ---"
# Fetches the centralized agent config from SSM Parameter Store and starts the agent.
# The IAM role on the Packer instance provides permission to do this.
sudo /opt/aws/amazon-cloudwatch-agent/bin/amazon-cloudwatch-agent-ctl \
  -a fetch-config \
  -m ec2 \
  -c ssm:AnvilCloudWatchAgentConfig -s

echo "--- [App AMI] Golden AMI Build Complete ---"
